cache:
    event:
        - $SD_SOURCE_DIR/.gradle
shared:
    image: java:7
jobs:
    gradle1:
        steps:
            - env: env
            - install: git clone https://github.com/gradle-guides/gradle-site-plugin.git && cd gradle-site-plugin && ./gradlew build
            - sleep: sleep 1000
        requires: [~commit, ~pr]
    gradle2-cache:
        steps:
            - ls: ls
            - install: git clone https://github.com/gradle-guides/gradle-site-plugin.git && cd gradle-site-plugin && ./gradlew build
        requires: [gradle1]
