# test
shared:
    image: node:6
jobs:
    test-get:
        steps:
            - env1: echo $SD_STORE_URL
            - env2: echo $SD_EVENT_ID
            - create: echo hi > /tmp/test
            - upload: "curl -H \"Authorization: Bearer $SD_TOKEN\" -H \"Content-Type: text/plain\" -X PUT \"https://beta.store.screwdriver.cd/v1/caches/events/$SD_EVENT_ID/mycache\" -T \"\/tmp\/test\"" 
            - install-cli: wget -q -O - https://github.com/screwdriver-cd/store-cli/releases/latest | egrep -o '/screwdriver-cd/store-cli/releases/download/v[0-9.]*/store-cli_linux_amd64' | wget --base=http://github.com/ -i - -O store-cli && chmod +x store-cli
            - sleep: sleep 10
            - cli-set: ./store-cli set mycache /tmp/test --type=cache --scope=events
            - cli-get: ./store-cli get mycache --type=cache --scope=events
            - ls: ls
        requires: [~pr, ~commit]
