shared:
    image: node:6
jobs:
    test:
        steps:
            - export: export HELLO=" 123 spaces ' singequote \" double quote "; echo $HELLO
            - secret: echo $MYSECRET
            - fail: failstuff
            - teardown-env: file=/tmp/exportEnv; cat $file; . $file; echo $HELLO; echo $MYSECRET
        requires: ~commit
        secrets:
            - MYSECRET
    test1:
        steps:
            - echo: echo bye
    test2:
        steps:
            - echo: echo bye
        requires: [~test, ~test1]
