cache:
    event:
        - $SD_SOURCE_DIR/node_modules
shared:
    image: node:6
jobs:
    job1:
        steps:
            - env
            - pwd
            - npm install
            - cd .. && store-cli set ./simpletest-beta/node_modules --type=cache --scope=event
        requires: [~commit, ~pr]
    job2-cache:
        steps:
            - ls0: ls
            - store-cli get ./node_modules --type=cache --scope=event
            - npm install
            - ls1: ls
        requires: [job1]
    job2-no-cache:
        steps:
            - ls0: ls
            - npm install
            - ls1: ls
        requires: [job1]
