cache:
    event:
        - /tmp/testcache
shared:
    image: node:6
jobs:
    job1:
        steps:
            - mkdir: mkdir /tmp/testcache
            - create-1: echo hi > /tmp/testcache/hi
            - create-2: echo bye > /tmp/testcache/bye
            - create-3: echo world > /tmp/testcache/world
            - cli-set: store-cli set /tmp/testcache/ --type=cache --scope=events
        requires: [~commit, ~pr]
    job2:
        steps:
            - cli-get: store-cli get --type=cache --scope=events
            - ls: ls
        requires: [job1]
