cache:
    event:
        - /tmp/testcache
shared:
    image: node:6
jobs:
    job1:
        steps:
            - mkdir: mkdir /tmp/testcache
            - create-1: echo hi > /tmp/testcache/hi
            - create-2: echo bye > /tmp/testcache/bye
            - create-3: echo world > /tmp/testcache/world
            - cli-set: store-cli set /tmp/testcache.zip --type=cache --scope=event
        requires: [~commit, ~pr]
    job2:
        steps:
            - cli-get: store-cli get /tmp/testcache --type=cache --scope=event
            - ls: ls /tmp
        requires: [job1]
    job11:
        steps:
            - npm install
            - pwd
            - cd .. && store-cli set ./simpletest-beta/node_modules --type=cache --scope=event
        requires: [~commit, ~pr]
    job22:
        steps:
            - ls0: ls
            - store-cli get ./node_modules --type=cache --scope=event
            - ls1: ls
        requires: [job11]
