shared:
    image: node:6
jobs:
    job1:
        steps:
            - env: env
            - install: npm install
        requires: [~commit, ~pr]
    job2-no-cache:
        steps:
            - ls: ls
            - install: npm install
        requires: [job1]
