shared:
    image: node:6
jobs:
    job1:
        steps:
            - mkdir: mkdir /tmp/testcache
            - create-1: echo hi > /tmp/testcache/hi
            - create-2: echo bye > /tmp/testcache/bye
            - create-3: echo world > /tmp/testcache/world
            - install-cli: wget -q -O - https://github.com/screwdriver-cd/store-cli/releases/v0.0.5 | egrep -o '/screwdriver-cd/store-cli/releases/download/v[0-9.]*/store-cli_linux_amd64' | wget --base=http://github.com/ -i - -O store-cli && chmod +x store-cli
            - cli-set: ./store-cli set mycache /tmp/testcache/ --type=cache --scope=events
        requires: [~commit, ~pr]
    job2:
        steps:
            - install-cli: wget -q -O - https://github.com/screwdriver-cd/store-cli/releases/v0.0.5 | egrep -o '/screwdriver-cd/store-cli/releases/download/v[0-9.]*/store-cli_linux_amd64' | wget --base=http://github.com/ -i - -O store-cli && chmod +x store-cli
            - ls1: ls
            - cli-get: ./store-cli get mycache --type=cache --scope=events
            - ls2: ls
        requires: [job1]
