cache:
    event:
        - $SD_SOURCE_DIR/node_modules
shared:
    image: node:6
jobs:
    job1:
        steps:
            - env
            - npm install
        requires: [~commit, ~pr]
    job2-cache:
        steps:
            - npm install
        requires: [job1]
