shared:
    image: node:6
jobs:
    test:
        steps:
            - export: export HELLO=" 123 spaces ' singequote \" double quote "; echo $HELLO
            - secret: echo $MYSECRET
            - ls: pwd; ls;
            - fail: env > /tmp/buildEnv; failstuff
            - teardown-env: . /sd/workspace/src/github.com/d2lam/simpletest-beta/script.sh; file=/tmp/buildEnv; cat $file; echo $HELLO; echo $MYSECRET
        requires: ~commit
        secrets:
            - MYSECRET
    test1:
        steps:
            - echo: echo bye
    test2:
        steps:
            - echo: echo bye
        requires: [~test, ~test1]
