shared:
    image: node:6
jobs:
    test:
        steps:
            - export: export HELLO=" 123 spaces ' singequote \" double quote "
            - secret: echo $MYSECRET
            - echo: prefix='export '; file=/tmp/buildEnv; newfile=/tmp/exportBuildEnv; env > $file; while read -r line; do echo ${prefix}$line; done < $file > $newfile; mv $newfile $file;
            - cat: cat /tmp/buildEnv
            - fail: failstuff
            - teardown-env: file=/tmp/buildEnv; . $file; rm $file; echo $HELLO; echo $MYSECRET
        requires: ~commit
        secrets:
            - MYSECRET
    test1:
        steps:
            - echo: echo bye
    test2:
        steps:
            - echo: echo bye
        requires: [~test, ~test1]
