cache:
    event:
        - $SD_SOURCE_DIR/node_modules
    pipeline:
        - ~/.gradle
    job:
        test-job: [/tmp/test]
shared:
    image: java:7
jobs:
    test-job:
        steps:
            - env: env
            - ls: ls /tmp/test
            - echo: echo hi > /tmp/test
        requires: [~commit, ~pr]
    npm1:
        steps:
            - install: npm install
        requires: [~commit, ~pr]
    npm2:
        steps:
            - install: npm install
        requires: [npm1]
    gradle:
        steps:
            - install: git clone https://github.com/gradle-guides/gradle-site-plugin.git && cd gradle-site-plugin && ./gradlew build
        requires: [~commit, ~pr]
